name: MacOS

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: macos-11.0

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          path: src

      - name: Configure
        run: |
          cmake -B build -S src -DCMAKE_INSTALL_PREFIX=$GITHUB_WORKSPACE/install

      - name: Build
        run: cmake --build build

      - name: Test
        run: |
          cd build
          ctest --output-on-failure

      - name: Install
        run: cmake --build build --target install
